### ISSUE TITLE
The generated example does not compile on ubuntu 22.04 with c++ std 20?

### ISSUE THREAD

**Issue by ClausKlein** [friendlyanon/cmake-init#105]
```bash
cmake-init -s -p conan --std 20 --examples cmake-init-modules
```
see https://github.com/ClausKlein/cmake-init-modules/actions/runs/8044764118
and https://github.com/ClausKlein/cmake-init-modules/pull/1

**Comment by friendlyanon** [comment]
Covered by https://github.com/friendlyanon/cmake-init/issues/104#issuecomment-1966967873  
I'll leave that one open until Conan 2.2 release.
