### ISSUE TITLE
Conan: add an option that would help choosing between generating a .txt or a .py file

### ISSUE THREAD

**Issue by sdmg15** [friendlyanon/cmake-init#109]
Hey thanks for writing this.
So it'd be nice to have such option. If this is a thing I'd love contributing by adding that.

**Comment by friendlyanon** [comment]
Seems reasonable. The reason I went with .py originally was because I wanted to make use of `default_options` and Conan 1 only had `[requires]` in the .txt version. I don't need the first one anymore and with Conan 2 there is now `[test_requires]` support in .txt as well.

**Comment by friendlyanon** [comment]
Unfortunately, using `[layout].cmake_layout` makes the generator output folder vary based on your profile. On Windows, it puts things in `build/generators` by default, but on \*nix systems it puts things in `build/<build_type>/generators`. You could make this consistent across all platforms by setting `tools.cmake.cmake_layout:build_folder_vars` in the profile, but that's additional setup necessary on the user's end.

I'd say this is a big enough issue that I will have to turn this down and stay with the `conanfile.py` solution. Reverted in ff48153
