### ISSUE TITLE
Build not working with conan

### ISSUE THREAD

**Issue by mike-5345** [friendlyanon/cmake-init#113]
Hello,

I initialized a project with conan as the package manager. After running `conan install . --build=missing` and `cmake --preset=dev`, running a build with `cmake --build --preset=dev` fails. The project is a library, and the library builds because I already have `fmt` installed on my machine, but the test exe does not compile because it cannot find the `Catch2` library that should be handled by conan.

I appreciate any help you can give me,
Mike

**Comment by friendlyanon** [comment]
`conan install . --build=missing` builds binaries for the build type specified in your profile, which is likely `Release`. The `dev` preset is for `Debug` builds. CMake will not use `Release` binaries for `Debug` builds by default.

Please read the generated `HACKING.md` document regarding Conan profiles and the appropriate command to invoke conan with.

**Comment by mike-5345** [comment]
This worked, thanks for the help!
