### ISSUE TITLE
Slowdown gif in the main readme

### ISSUE THREAD

**Issue by YarikTH** [friendlyanon/cmake-init#13]
Currently, gif in the main readme played incredibly fast. There is a lot of text there, interesting text that advertised the library, but I can't read it because of the speed. It seems it needs a 5-10x slowdown to be useful.

**Comment by friendlyanon** [comment]
What do you think of this?

![my](https://user-images.githubusercontent.com/1736896/126867939-37868ca7-eba9-4e1a-9160-024cd6d0edff.gif)

**Comment by YarikTH** [comment]
Almost ideally. All the text is readable and can be researched in several loops. Sometimes looks like a slow-mo though but I can't catch the exact details of this feeling. Anyway, it is way better than the previous version that was almost unreadable.

**Comment by friendlyanon** [comment]
The GIF was supposed to show the flow more when using cmake-init, not the textual content itself, but if this helps you grasp things more easily, then that's a good thing.
