### ISSUE TITLE
Python packaging

### ISSUE THREAD

**Issue by friendlyanon** [friendlyanon/cmake-init#3]
[`zipapp`](https://docs.python.org/3/library/zipapp.html) is used to create a self-contained runnable artifact, but I'm not sure if this is the best way to go about things.

[This hack](https://github.com/friendlyanon/cmake-init/blob/0c1a074ab576863cde3caf423dab5381c208a78c/cmake-init/__main__.py#L280) is also not something I like to see in the code, but after local testing, this is the only thing that stopped Python from closing the file handle to the zip.

**Comment by GavinRay97** [comment]
What about just using amalgamation to extract all files and dependency modules into a single `.py` file:

https://github.com/Akrog/pinliner
https://pypi.org/project/amalgamate/

Then you just have a single-file Python distribution, like a single-header C library.

**Comment by friendlyanon** [comment]
From what I read those links only deal with python packages, not with assets bundled with packages.

The ideal solution would treat the `.py` and `.pyz` cases equally. The `pkgutil` module would be nice if it didn't require hardcoding the paths, which are already given with the directory structure.

**Comment by friendlyanon** [comment]
65785da5beff83390e66afb502d9c193287cb3cf introduced PyPI packaging. It feels a little hacky.

**Comment by friendlyanon** [comment]
I guess this can be closed. The current workflow works.
