### ISSUE TITLE
Could not read presets: Unrecognized "version" field

### ISSUE THREAD

**Issue by fschutt** [friendlyanon/cmake-init#37]
I've followed the instructions exactly, using cmake-init v0.24.0. But when I do `cd cpptest && cmake --preset=dev`, I only get the error:

```
CMake Error: Could not read presets from 
C:/Users/Felix Schütt/Development/cpptest: Unrecognized "version" field
```

I've uploaded the code generated by cmake-init here for debugging: https://github.com/fschutt/cpptest

cmake 3.19.1
cmake-init 0.24.0
Windows 8.1
clang 12.0.0
target:  x86_64-pc-windows-msvc

**Comment by friendlyanon** [comment]
[Install](https://github.com/friendlyanon/cmake-init#install):

> Make sure you have these programs installed:
>
> - CMake 3.20 or newer

Reason: #34's closing commit
