### ISSUE TITLE
Default dependencies for C project when using a package manager

### ISSUE THREAD

**Issue by friendlyanon** [friendlyanon/cmake-init#47]
Related to #42

I looked at the available dependencies in Conan Center Index for C and there doesn't seem to be one that strikes me as one that would be nice to use as a default to have as an example. For C++ project, the obvious defaults are fmt (dependency) and Catch2 (dev dependency).

One that I think could be okay is [json-c](https://github.com/json-c/json-c), because it has a proper CMake package that can be consistently consumed via either package managers. This makes setting the install config up for library type projects trivial.  
I haven't look at a dev dependency for C projects yet.

**Comment by cdecompilador** [comment]
I think this would be a good idea using the `FetchContent` feature in cmake by default (also having the option to select (vcpkg, etc, ...)

For example:
```cmake
# --- External dependencies ---
FetchContent_Declare(
        Cli
        GIT_REPOSITORY "https://github.com/daniele77/cli.git"
        GIT_TAG "63eb02970fc19c2ba182be4c30d5dcd79e63f438"
)
FetchContent_MakeAvailable(Cli)
set(EXTERNAL_DEPS "cli")
```

I though that having a `cmake-add` command would also be great but that would be harder to implement, for example doing a `cmake-add fmtlib/fmt` would look in the common remote git repository providers for user `fmtlib` with repository `fmt` and add the respective `FetchContent` with the last commit, also a `cmake-rm` or `cmake-update` but these are just ideas.

**Comment by friendlyanon** [comment]
`FetchContent` is a form of vendoring that I heavily recommend against. For some things, it's just fine, like fetching `m.css` to generate docs. It's a purely developer process and it is opt-in even in developer mode.

For dependencies, it absolutely should not be used. `add_subdirectory` is not a package manager. https://github.com/friendlyanon/cmake-init/commit/a4a86d897efb8aec548bd5431c1b791f4c349fe5 implements a tiny template engine for more complex templates, which will allow me to add PM code to generated projects.

**Comment by cdecompilador** [comment]
Yeah, thinking about it, linking this tool to the project structure would remove cmake potential.

**Comment by friendlyanon** [comment]
C projects have https://github.com/json-c/json-c as a dependency and https://github.com/catchorg/Catch2 as a dev dependency. I couldn't find a nice C testing library with the necessary CMake integration. See 05bfbfbfa2c8130ed3ef1ff1c6d6fa02fc1d1212
