### ISSUE TITLE
Header install path has a redundant component

### ISSUE THREAD

**Issue by bustercopley** [friendlyanon/cmake-init#49]
After installing the [default header-only project](https://github.com/friendlyanon/cmake-init-header-only), the end-user would include the header like this:
```
#include <header-only/header-only/header-only.hpp>
```
Is that intentional? I would guess most maintainers would want to delete one of those path components,
```diff
modified   cmake/install-rules.cmake
@@ -1,5 +1,5 @@
 if(PROJECT_IS_TOP_LEVEL)
-  set(CMAKE_INSTALL_INCLUDEDIR include/header-only CACHE PATH "")
+  set(CMAKE_INSTALL_INCLUDEDIR include CACHE PATH "")
 endif()
 
 # Project is configured with no languages, so tell GNUInstallDirs the lib dir
```

**Comment by friendlyanon** [comment]
See https://github.com/friendlyanon/cmake-init/issues/43

I will pin that issue, since this is the second time it's brought up. If you have further comments on the matter, please post them in that issue.
