### ISSUE TITLE
Mingw support in cmake-init

### ISSUE THREAD

**Issue by RamakrishnanOSS** [friendlyanon/cmake-init#89]
This project is awesome. Support Mingw could also be interesting..

{
      "name": "win32-gcc-x64-mingw-debug",
      "inherits": ["ci-std", "conan"],
      "displayName": "Windows GCC x64 (MinGW Makefiles) Debug",
      "description": "Using GCC x64 compiler with \"MinGW Makefiles\" geneartor on Windows - Debug",
      "generator": "MinGW Makefiles",
      "binaryDir": "${sourceDir}/build/${presetName}",
      "installDir": "${sourceDir}/install/${presetName}",
      "cacheVariables": {
        "CMAKE_C_COMPILER": "C:/msys64/mingw64/bin/gcc.exe",
        "CMAKE_CXX_COMPILER": "C:/msys64/mingw64/bin/g++.exe",
        "CMAKE_MAKE_PROGRAM": "C:/msys64/mingw64/bin/mingw32-make.exe",
        "CMAKE_BUILD_TYPE": "Debug"
      },
	  "hidden": true
    },

**Comment by friendlyanon** [comment]
There doesn't need to be any work done on cmake-init's side. I just tried doing `choco install mingw` and I could build a CMake project just fine with `cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-g++.exe`.

You are welcome (and encouraged!) to modify your own presets, but the default of using MSVC on Windows introduces the least amount of friction for cmake-init.
