### ISSUE TITLE
Errors with `-fcf-protection=full` on darwin (CMakePresets.json, "flags-darwin" preset)

### ISSUE THREAD

**Issue by lkk7** [friendlyanon/cmake-init#95]
Hi. The flag`-fcf-protection=full` causes
```
    error: option 'cf-protection=return' cannot be specified on this target
    error: option 'cf-protection=branch' cannot be specified on this target
```
On a M1 Macbook (clang 14.0.3).

Should it be deleted? Looks like this flag is Intel-only for now, and Macs are shifting towards M1/M2s. 
(`CMakePresets.json`, in `"flags-darwin"` preset. I can do the pull request if you decide so)

**Comment by friendlyanon** [comment]
> Should it be deleted? Looks like this flag is Intel-only for now, and Macs are shifting towards M1/M2s.

Yes, it looks like that's what needs to happen. From a quick search it looks like the control flow protection relies on hardware support: https://en.wikipedia.org/wiki/Indirect_Branch_Tracking

ARM gained such a technology in - the pretty recent - version 9 of its specification and I don't know which version the Apple chips implement. Control flow protection will likely not be available for a while.

**Comment by friendlyanon** [comment]
I'll make a release with the fix now, since I don't have anything else in the works.
