### ISSUE TITLE
Runtime error (Error code: 0xc0000135) when building shared libraries on Windows using MSVC

### ISSUE THREAD

**Issue by HoussamCzn** [friendlyanon/cmake-init#97]
## Description

When building shared libraries on Windows using MSVC and setting ``BUILD_SHARED_LIBS`` to ON, I get a runtime error with exit code 0xc0000135, likely because it's not in the same directory as the shared object.

## Steps to Reproduce
- Set ``BUILD_SHARED_LIBS`` to ON.
- Build the project using MSVC.
- Try running a unit test (in my case)

## Expected behavior

The unit test runs without any errors.

## Actual behavior

The unit test exits with error code 0xc0000135.

## Additional context
- This issue seems specific to Windows; building shared libraries on Linux or Mac doesn't produce the same error.
- The problem appears to be that the shared object isn't located alongside its .dll.

Is there a way to address this or could this be a bug? For now, I just manually copy the missing dll when building unit tests.

**Comment by friendlyanon** [comment]
> likely because it's not in the same directory as the shared object

This is correct and I do not plan on changing it. It's also documented in the generated documents. To quote HACKING.md:

---

## Running tests on Windows with `BUILD_SHARED_LIBS=ON`

If you are building a shared library on Windows, you must add the path to the
DLL file to `PATH` when you want to run tests. One way you could do that is by
using PowerShell and writing a script for it, e.g. `env.ps1` at the project
root:

```powershell
$oldPrompt = (Get-Command prompt).ScriptBlock

function prompt() { "(Debug) $(& $oldPrompt)" }

$VsInstallPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -Property InstallationPath
$Env:Path += ";$VsInstallPath\Common7\IDE;$Pwd\build\dev\Debug"
```

Then you can source this script by running `. env.ps1`. This particular
example will only work for Debug builds.

---

This is the only reasonable way to deal with DLLs at this stage of development. You are already required to activate the vcvars environment for the MSVC toolchain if you want to build from the command line using Ninja anyway: https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#developer_command_file_locations

**Comment by HoussamCzn** [comment]
Oh, it seems like I missed that in HACKING.md. Thanks for pointing that out then!

**Comment by friendlyanon** [comment]
Now that I look at that section, it's not documented why `$VsInstallPath\Common7\IDE` is also added to the `PATH`. That's supposed to enable you to launch Visual Studio from that command line (`devenv`) to inherit the environment. Same goes for other editors, such as Visual Studio Code (`code`), vim (`vim`), etc.

**Comment by friendlyanon** [comment]
I'm going to close this, since this is documented already.
