### ISSUE TITLE
Setting `-D<project>_INSTALL_CMAKEDIR=something` produces unexpected results

### ISSUE THREAD

**Issue by ekilmer** [friendlyanon/cmake-init#98]
I noticed that setting the `<project>_INSTALL_CMAKEDIR` cache variable on the CLI will install the cmake files in the _current working directory_, instead of the installation prefix, if you don't specify the variable type. I am on CMake 3.27.7, cmake-init 0.37.3, and macOS (but hopefully OS doesn't make a difference).

## Potential Fix

I've tested that this can be fixed by setting the type of `<project>_INSTALL_CMAKEDIR` to `STRING` instead of `PATH` in the `cmake/install_rules.cmake` file.

## Reproducing

Initialize a project with
```sh
cmake-init -s ./test-project
```

Configure the project with our custom `<project>_INSTALL_CMAKEDIR` directory and build the project:
```sh
cmake -B build -S ./test-project -Dtest-project_INSTALL_CMAKEDIR=something
cmake --build build
```

However, during installation, you'll notice that instead of installing underneath the specified installation prefix (`install/subdir`), it installs to the current working directory (last 4 lines):

```sh
$ cmake --install build --prefix install/subdir
-- Install configuration: ""
-- Installing: /tmp/work/install/subdir/include/test-project-0.1.0
-- Installing: /tmp/work/install/subdir/include/test-project-0.1.0/test-project
-- Installing: /tmp/work/install/subdir/include/test-project-0.1.0/test-project/test-project.hpp
-- Up-to-date: /tmp/work/install/subdir/include/test-project-0.1.0
-- Up-to-date: /tmp/work/install/subdir/include/test-project-0.1.0/test-project
-- Installing: /tmp/work/install/subdir/include/test-project-0.1.0/test-project/test-project_export.hpp
-- Installing: /tmp/work/install/subdir/lib/libtest-project.a
-- Installing: /tmp/work/something/test-projectConfig.cmake
-- Installing: /tmp/work/something/test-projectConfigVersion.cmake
-- Installing: /tmp/work/something/test-projectTargets.cmake
-- Installing: /tmp/work/something/test-projectTargets-noconfig.cmake
```

Weirdly, specifying the type of variable (either `STRING` or `PATH`) on the CLI will produce the correct behavior:

`STRING`

```sh
$ cmake -B build-string -S ./test-project -Dtest-project_INSTALL_CMAKEDIR:STRING=something
[...]
$ cmake --build build-string
[...]
$ cmake --install build-string --prefix install/string
-- Install configuration: ""
-- Installing: /tmp/work/install/string/include/test-project-0.1.0
-- Installing: /tmp/work/install/string/include/test-project-0.1.0/test-project
-- Installing: /tmp/work/install/string/include/test-project-0.1.0/test-project/test-project.hpp
-- Up-to-date: /tmp/work/install/string/include/test-project-0.1.0
-- Up-to-date: /tmp/work/install/string/include/test-project-0.1.0/test-project
-- Installing: /tmp/work/install/string/include/test-project-0.1.0/test-project/test-project_export.hpp
-- Installing: /tmp/work/install/string/lib/libtest-project.a
-- Installing: /tmp/work/install/string/something/test-projectConfig.cmake
-- Installing: /tmp/work/install/string/something/test-projectConfigVersion.cmake
-- Installing: /tmp/work/install/string/something/test-projectTargets.cmake
-- Installing: /tmp/work/install/string/something/test-projectTargets-noconfig.cmake
```

`PATH`

```sh
$ cmake -B build-path -S ./test-project -Dtest-project_INSTALL_CMAKEDIR:PATH=something
[...]
$ cmake --build build-path
[...]
$ cmake --install build-path --prefix install/path
-- Install configuration: ""
-- Installing: /tmp/work/install/path/include/test-project-0.1.0
-- Installing: /tmp/work/install/path/include/test-project-0.1.0/test-project
-- Installing: /tmp/work/install/path/include/test-project-0.1.0/test-project/test-project.hpp
-- Up-to-date: /tmp/work/install/path/include/test-project-0.1.0
-- Up-to-date: /tmp/work/install/path/include/test-project-0.1.0/test-project
-- Installing: /tmp/work/install/path/include/test-project-0.1.0/test-project/test-project_export.hpp
-- Installing: /tmp/work/install/path/lib/libtest-project.a
-- Installing: /tmp/work/install/path/something/test-projectConfig.cmake
-- Installing: /tmp/work/install/path/something/test-projectConfigVersion.cmake
-- Installing: /tmp/work/install/path/something/test-projectTargets.cmake
-- Installing: /tmp/work/install/path/something/test-projectTargets-noconfig.cmake
```

**Comment by friendlyanon** [comment]
`<project>_INSTALL_CMAKEDIR` is a `PATH` variable like the `CMAKE_INSTALL_*DIR` variables, however `GNUInstallDirs` does extra things to only adjust the type of an existing cache variable without completely reevaluating it. https://github.com/Kitware/CMake/blob/1b91d6046a71d9c777fcaac398f5e32d162ed7c5/Modules/GNUInstallDirs.cmake#L149  
If you pass a typed variable definition, then this reevaluation won't occur.

**Comment by ekilmer** [comment]
Ah! Thank you for the link to the `set` documentation. It all makes sense now, but that seems quite subtle in this case, especially because passing something like `-DCMAKE_INSTALL_LIBDIR=something` does the correct and expected thing (due to the conversion helpers in `GNUInstallDirs` that you linked).

```sh
$ cmake-init -s ./test-project
[...]
$ cmake -B build -S ./test-project -DCMAKE_INSTALL_LIBDIR=something
[...]
$ cmake --build build
[...]
$ cmake --install build --prefix install/subdir
-- Install configuration: ""
-- Installing: /tmp/work/install/subdir/include/test-project-0.1.0
-- Installing: /tmp/work/install/subdir/include/test-project-0.1.0/test-project
-- Installing: /tmp/work/install/subdir/include/test-project-0.1.0/test-project/test-project.hpp
-- Up-to-date: /tmp/work/install/subdir/include/test-project-0.1.0
-- Up-to-date: /tmp/work/install/subdir/include/test-project-0.1.0/test-project
-- Installing: /tmp/work/install/subdir/include/test-project-0.1.0/test-project/test-project_export.hpp
-- Installing: /tmp/work/install/subdir/something/libtest-project.a
-- Installing: /tmp/work/install/subdir/something/cmake/test-project/test-projectConfig.cmake
-- Installing: /tmp/work/install/subdir/something/cmake/test-project/test-projectConfigVersion.cmake
-- Installing: /tmp/work/install/subdir/something/cmake/test-project/test-projectTargets.cmake
-- Installing: /tmp/work/install/subdir/something/cmake/test-project/test-projectTargets-noconfig.cmake
```

Note that setting `-DCMAKE_INSTALL_INCLUDEDIR=something` also produces the same result as `<project>_INSTALL_CMAKEDIR` for cmake-init projects, due to declaring it a `PATH` before `GNUInstallDirs` can handle it. So, that would also need to change to `STRING` if `<project>_INSTALL_CMAKEDIR` were changed.

I'm leaning on the side of _least surprise_ in the usage of `<project>_INSTALL_CMAKEDIR` and `CMAKE_INSTALL_INCLUDEDIR` to behave like the other variables provided by `GNUInstallDirs`, and change it to type `STRING`. But, I understand that might cause some confusion because the `GNUInstallDirs` documentation says they are of type `PATH`.

Regardless, being explicit about the type of variable passed on the CLI is always better, so I guess that should be promoted more often.

Aside: This issue has bitten me during vcpkg packaging. It even appears to affect the (albeit, seemingly unused and undistributed) `portfile.cmake` in this repo

https://github.com/friendlyanon/cmake-init/blob/069946dd2eae2c369b79bfde9c518ee45b0f8b52/cmake-init/templates/vcpkg/portfile.cmake#L29

However, vcpkg has the ability to handle relocating the installed CMake config files by default, so it's not necessary to set it, as evidenced in your [vcpkg example](https://github.com/friendlyanon/cmake-init-vcpkg-example/blob/master/ports/cmake-init-shared-static/portfile.cmake), but if the package installs other supporting CMake files, then they probably won't be relocated and would cause issues for relative file lookup/inclusion.

Thoughts?

**Comment by friendlyanon** [comment]
I think the vcpkg subcommand should be gone. I haven't really used it myself and I think it's just better to look at the vcpkg repo for ports instead. For overlay ports, there is already the wiki for an example.

About the variables, I'm thinking of applying this patch:

```patch
diff --git a/cmake-init/templates/common/cmake/install-rules.cmake b/cmake-init/templates/common/cmake/install-rules.cmake
index 1131443..5d4ae8c 100644
--- a/cmake-init/templates/common/cmake/install-rules.cmake
+++ b/cmake-init/templates/common/cmake/install-rules.cmake
@@ -1,8 +1,9 @@
 {% if not exe %}if(PROJECT_IS_TOP_LEVEL)
   set(
       CMAKE_INSTALL_INCLUDEDIR "include/{= name =}-${PROJECT_VERSION}"
-      CACHE PATH ""
+      CACHE STRING ""
   )
+  set_property(CACHE CMAKE_INSTALL_INCLUDEDIR PROPERTY TYPE PATH)
 endif(){% if header %}
 
 # Project is configured with no languages, so tell GNUInstallDirs the lib dir
@@ -47,8 +48,9 @@ write_basic_package_version_file(
 # Allow package maintainers to freely override the path for the configs
 set(
     {= name =}_INSTALL_CMAKEDIR "{% if lib %}${CMAKE_INSTALL_LIBDIR}/cmake{% else %}${CMAKE_INSTALL_DATADIR}{% end %}/${package}"
-    CACHE PATH "CMake package config location relative to the install prefix"
+    CACHE STRING "CMake package config location relative to the install prefix"
 )
+set_property(CACHE {= name =}_INSTALL_CMAKEDIR PROPERTY TYPE PATH)
 mark_as_advanced({= name =}_INSTALL_CMAKEDIR)
 
 install(
```

This adds some code whose purpose is not necessarily clear at first, but at least it won't result in unexpected behavior with untyped variables coming from the command line.

**Comment by ekilmer** [comment]
> I think the vcpkg subcommand should be gone. I haven't really used it myself and I think it's just better to look at the vcpkg repo for ports instead. For overlay ports, there is already the wiki for an example.

Ah! I missed/misunderstood that command and have not used it. I agree it's better to look at the vcpkg repo and/or the example in the wiki.

The patch looks good and works well for me! Thank you!
